dist: trusty

language: node_js

node_js:
  - "10"
  - "12"
  - "13"

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  npm: false

before_script:
  - npm install

script:
  - npm run test
