dist: trusty

language: node_js

node_js:
  - "8"
  - "10"
  - "12"
  - "13"
  - "14"

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - main
    - development

cache:
  npm: false

before_script:
  - npm install

script:
  - npm run test

after_success:
  - ./node_modules/.bin/codecov --token=CODECOV_TOKEN
